from enum import Enum

class ImageState(str, Enum):
    AUTHENTIC = "AUTHENTIC"
    AUTHENTIC_DIGITALLY_RETOUCHED = "AUTHENTIC_DIGITALLY_RETOUCHED"
    TRADITIONALLY_MANIPULATED = "TRADITIONALLY_MANIPULATED"
    AI_ASSISTED = "AI_ASSISTED"
    AI_GENERATED = "AI_GENERATED"
    AI_MANIPULATED = "AI_MANIPULATED"
    INCONCLUSIVE = "INCONCLUSIVE"
